## This manifest deploys CredHub and a co-located PostgreSQL database. This configuration assumes that you have an existing UAA deployed at a known location for authentication. 
## 
## This deployment is intended for development testing only. You will lose all of your stored data in the event of an issue with the VM or mounted disks. 
## 
## This manifest is not regularly maintained and may fall out of date.
## 
## This manifest assumes that you are deploying with a BOSH Director that has CredHub enabled. If this is not the case, you must replace the values below with ((variable)) syntax with actual values. If you are using BOSH with CredHub enabled, these values will be generated automatically, with the exception of '/uaa/jwt', which you must set to the public verification key for you UAA provider.
## 
## You must update the vm_type (currently 'medium') and network name (currently 'west') according to your cloud config. You must also replace the external_ip and uaa_url with an accurate values. 
---
name: sample-credhub-postgres

releases:
- name: credhub
  version: latest
- name: postgres
  version: latest

stemcells: 
- alias: default 
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  update_watch_time: 10000-200000
  canary_watch_time: 10000-200000

variables:
- name: credhub-encryption-password
  type: password
  options:
    length: 40
- name: credhub-ca
  type: certificate
  options:
    is_ca: true
    common_name: CredHub CA
- name: credhub-tls
  type: certificate
  options:
    ca: credhub-ca
    common_name: ((external-ip-address))
    alternative_names:
    - ((external-ip-address))
    - ((internal-ip-address))
    - 127.0.0.1
- name: database-tls
  type: certificate
  options: 
    ca: credhub-ca
    common_name: ((external-ip-address))
    alternative_names:
    - ((external-ip-address))
    - ((internal-ip-address))
    - 127.0.0.1
- name: database-admin
  type: password

instance_groups:
- name: credhub
  instances: 1
  vm_type: medium
  azs: [z1]
  stemcell: default
  networks:
  - name: default
    static_ips: [((internal-ip-address))]
    default: [dns, gateway]
  - name: public
    static_ips: [((external-ip-address))]

  jobs:
  - name: credhub
    release: credhub
    properties:
      credhub:
        tls: ((credhub-tls))
        authentication:
          uaa:
            url: ((uaa-url))
            verification_key: ((uaa-jwt))
            ca_certs:
            - ((uaa-tls))
        data_storage:
          type: postgres
          username: admin
          password: ((database-admin))
          host: 127.0.0.1
          port: 5432
          database: credhub
          require_tls: true
          tls_ca: ((database-tls.ca))
        encryption:
          keys: 
          - provider_name: int
            encryption_password: ((credhub-encryption-password))
            active: true
          providers: 
          - name: int
            type: internal

  - name: postgres
    release: postgres
    properties: 
      databases:
        address: 127.0.0.1
        port: 5432
        databases: 
        - name: credhub
        roles: 
        - name: admin
          password: ((database-admin))
        tls: 
          ca: ((database-tls.ca))
          certificate: ((database-tls.certificate))
          private_key: ((database-tls.private_key))

